name: Release Resource Pack

on:
  release:
    types: 
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create the .zip file for the resource pack
        run: |
          zip -r "hypergrowth-${{ github.event.release.tag_name }}.zip"

      - name: Upload the zip file to the release
        uses: softprops/action-gh-release@v1
        with:
          files: "hypergrowth-${{ github.event.release.tag_name }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}